name: Generate Activity Graph

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ARYANBUILDS707
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: activity-graph.svg
          options: >-
            bg_color=050816&
            color=E6F7FF&
            line=00D9FF&
            point=00AEEF&
            area_color=008CFF&
            area=true&
            hide_border=true&
            custom_title=ARYANBUILDS707%20-%20Contribution%20Activity&
            radius=8&
            height=300

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Copy activity graph
        run: |
          cp ../activity-graph.svg ./activity-graph.svg

      - name: Commit activity graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity-graph.svg
          git commit -m "Update activity graph" || exit 0
          git push origin output
